export let componentManifest = {
	browser: "browser.js",
	files: [
		"svg/",
		"dist/",
		"browser.js",
		"src/",
		"!src/**/*.js",
		"main.scss",
		"img",
		"*.json",
		"*.js",
		"!main.js",
		"scss",
		"!bower.json",
		"!.bower.json",
	],
	eslintIgnore: ["browser.js", "dist/"],
	keywords: ["origami", "component", "ft"],
}
